### ISSUE TITLE
isTagRemovable can't be set to false from element property 

### ISSUE THREAD

**Issue by basvanbeek** [PolymerEl/paper-tags#11]
In Polymer 1.0 a boolean attribute can't default to true as there is no way to unset / set to false. If the attribute regardless of value is found it means true, false can occur only when omitting the attribute.

```
<my-element my-prop="false"></my-element>
```

In above example `myProp` will evaluate to `true`

See: https://www.polymer-project.org/1.0/docs/devguide/properties#configuring-boolean-properties

**Comment by christophe-g** [comment]
Thanks @basvanbeek .
Yes you are right - this component was my first try out with Polymer a couple of month back. That is the type of mistakes you make then ; ) 

Note to self:
This property should now be `preventRemoveTag`, defaulted to false. 

C.

**Comment by christophe-g** [comment]
resolved via https://github.com/PolymerEl/paper-tags/commit/d54eab88b8ce27ffc04b002aff3eaa5b48f65ee6
C.
