### ISSUE TITLE
when set paper-tags-dropdown readonly,it also can click and display dropdown item;

### ISSUE THREAD

**Issue by vitawt** [PolymerEl/paper-tags#19]
hi , it's my first time to submit an issue, sorry for my poor english;
just like the title, I set paper-tags-dropdown readonly or disabled , that i won't the element can be clicked. But it can't work; How can i fix it ?

**Comment by christophe-g** [comment]
Hey, 
Thanks for your first issue. 

I have added `readonly`  and `disabled` property on the new release (v1.5.0) of `paper-tags-dropdown`

**Comment by vitawt** [comment]
Thank you very much; 
I have tried and it worked , but it must declare readonly and disabled at the same time .
If it can just set readonly but not disabled, like paper-dropdown-menu, and removed the icon on right
