### ISSUE TITLE
apply paper-tags-item style inside paper-tags-dropdown

### ISSUE THREAD

**Issue by keithstric** [PolymerEl/paper-tags#22]
How do I apply the --paper-tags-item custom style mixin when using the paper-tags-dropdown? I've tried all kinds of combinations and have been unsuccessful so far.

**Comment by christophe-g** [comment]
In v.2.0.1, added a mixin that can be applied in paper-tags-dropdown.html to allow this: 

```css
  paper-tags-input {
      apply --paper-tags-dropdown-input;
    }
```
