### ISSUE TITLE
Polymer 2 support?

### ISSUE THREAD

**Issue by dlannan** [PolymerEl/paper-tags#25]
Two things concern me about this "feature"
- No issues are being answered about it
- It seems support for Polymer 2 is less than good. 
Is there any likelihood of this becoming Polymer 2 compatible or, is there a way to get it working in Polymer 2. 

The type of faults Im getting is:
`Cannot read property 'tagInput' of undefined.`

And other warnings related to Polymer 2 compatibility.
Any help/ideas/support would be appreciated.

**Comment by vlucian** [comment]
I have the same issue: tried to use it in a polymer 2 project and encountered some version issues...

**Comment by auguster** [comment]
We ported most of the code to Polymer 2.0 but we don't have the time to finish up... Should I open a PR anyway ? https://github.com/Weaverize/paper-tags

**Comment by christophe-g** [comment]
Bonjour @auguster - yes, please do. 

We will be porting one of our app using paper-tag to Polymer 2.0 shortly (May). Upgrading Paper-tag is in the pipeline - thanks!

**Comment by AlexanderYZhang** [comment]
If anyone is interested, I needed a polymer 2.0 version pretty fast so I pulled the work from  [https://github.com/Weaverize/paper-tags](https://github.com/Weaverize/paper-tags) and finished it up while also updating it with the recent changes from this repo.
[https://github.com/AlexanderYZhang/paper-tags](https://github.com/AlexanderYZhang/paper-tags)

**Comment by christophe-g** [comment]
@AlexanderYZhang - Thanks a lot for this work. It might "inspire" me when I find time to upgrade this component to 2.0.

**Comment by auguster** [comment]
@AlexanderYZhang great !
If you want, you can PR on our repo (https://github.com/Weaverize/paper-tags). We'll probably work on it again when we migrate to Polymer 3 ;-)

**Comment by AlexanderYZhang** [comment]
@christophe-g haha sounds good! It works on polymer2 for me but I had to do some changes so I hope I didn't break anything. Great work on the paper-tags btw!

@auguster I made a pull request. I needed a bit of functionality and did a few quick fixes just for my app so I was a little apprehensive at making a pull request but it'd be awesome to have a more eyes looking at it!

**Comment by auguster** [comment]
@AlexanderYZhang don't worry, we'll review the code before we accept the merge. It's important to PR to have due credit for your work ;-)

**Comment by RoMay** [comment]
@AlexanderYZhang  @auguster hi guys, any advice how to get working in Polymer 3 application?

**Comment by AlexanderYZhang** [comment]
@RoMay My application isn't up to 3.0 yet so I haven't taken a look at that yet but here is the upgrade guide if you haven't seen it already: https://www.polymer-project.org/3.0/docs/upgrade

You can take a look at my repo for a working Polymer2 base if you want.
https://github.com/AlexanderYZhang/paper-tags/tree/polymer2

**Comment by christophe-g** [comment]
Closed by https://github.com/PolymerEl/paper-tags/releases/tag/v2.0.0

Thanks a lot to contributers (@auguster, @AlexanderYZhang )!

**Comment by auguster** [comment]
No problem ;-)

We'll probably do a similar work when we migrate to Polymer 3, though it's not in our roadmap yet @weaverize.

@RoMay sorry, we haven't taken more than a glimpse at Polymer 3 as of now. We hope that the API stabilize in the futur because porting from 1.0 to 2.0 has be a hassle. Just when we finished porting to 2.0, 3.0 comes out with completely different paradigm -_-'

**Comment by christophe-g** [comment]
@auguster  - same impression here. 

Also have a 3.0 migration somewhere in out roadmap, but not convinced about latest Polymer direction as I really prefer a markup-centric approach to application building. 

Anyway, greetings from Lyon!
