### ISSUE TITLE
Auto-transpile to legacy element syntax

### ISSUE THREAD

**Issue by bpetridean** [PolymerEl/paper-tags#32]
Hi,
Is there a quick/automated way that I could use to transpile paper-tags `master` branch to legacy syntax? e.g. https://polymer-library.polymer-project.org/3.0/docs/devguide/legacy-elements
The latest tag providing this support was 1.8.1, but in there polymer1.x is still being used and my intention is to use polymer2 elements.

Extended context:
I am planning to use polymer2 version of paper-tags from java.
I am using a forked version of vaadin's gwt-api-generator tool to generate the wrappers given the above wc, but it only handles legacy element syntax - defined using the Polymer factory, thus my question.

Thank you.

**Comment by christophe-g** [comment]
Hey, 
thanks for reaching out. 

I suppose this is the core of the problem (https://github.com/manolo/gwt-api-generator): 
> Currently the generator only supports Web Components written in Polymer 1.0 syntax. Support for other type of JavaScript sources might be added in the future.

In this case, I would then recommend using an older version of paper-tags, which was using Polymer 1.x. 

However, I would not feel confident to rely on a generator tool that only support Polymer 1.x. ; )

**Comment by bpetridean** [comment]
Hi,

> In this case, I would then recommend using an older version of paper-tags, which was using Polymer 1.x.

I am using polymer-2x elements with the gwt-api-generator (separate fork), but it still requires that `Polymer` factory method is used, thus my question: paper-tags polymer-2x version defined using Polymer factory method (instead of ES6).

> In this case, I would then recommend using an older version of paper-tags, which was using Polymer 1.x.

I have tried tag 1.8.1, out of curiosity, but it fails as it is unable to find paper-menu component...and I did not dig deeper as I moved away from polymer-1x

**Comment by christophe-g** [comment]
All right, 

I am unfortunately not aware of a quick/automated way to transpile ES6 back to legacy syntax.

**Comment by bpetridean** [comment]
I see,

Thank you.
